version: "3"

services:
    app:
      build:
        context: ./
      env_file: .env.dev
      image: deegreed:${WORKSPACE:-dev}
      ports:
        - 1337:8080
      volumes: 
        - ./workspaces:/root/.deegree:rw
